Bump gitleaks/gitleaks from 8.18.0 to 8.18.1

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,7 +15,7 @@ runs:
   steps:
     - name: Fail
       if: ${{ runner.os != 'Windows' }}
-      run: echo "::error::${{ runner.os }} ${{ runner.arch }} is not supported" && exit 1
+      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
       shell: sh
     - name: Collect info
       if: ${{ runner.os == 'Windows' }}
@@ -28,11 +28,13 @@ runs:
       shell: sh
     - name: Install npiet
       if: ${{ steps.info.outputs.NPIET_INSTALLED == 'false' && runner.os == 'Windows' }}
+      env:
+        INPUT_VERSION: "${{ inputs.version }}"
       run: |
-        if ("${{ inputs.version }}" -eq "1.1") {
-          $Version="${{ inputs.version }}"
+        if ("${INPUT_VERSION}" -eq "1.1") {
+          $Version="${INPUT_VERSION}"
         } else {
-          $Version="${{ inputs.version }}a"
+          $Version="${INPUT_VERSION}a"
         }
         Invoke-WebRequest -URI "http://www.bertnase.de/npiet/npiet-$Version-win32.zip" -OutFile npiet.zip
         Expand-Archive npiet.zip -DestinationPath .
