Bump prettier from 3.4.2 to 3.6.2

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,7 +25,9 @@ runs:
   steps:
     - name: Fail
       if: ${{ runner.os != 'Windows' }}
-      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
+      run: |
+        echo "::error title=OS is not supported::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
+        exit 1
       shell: sh
 
     - name: Collect info
@@ -49,7 +51,7 @@ runs:
       shell: pwsh
       working-directory: "${{ github.action_path }}/src"
 
-    - name: Print version
+    - name: Print location
       run: |
         . ./logging.sh
         log_info "npiet is located at $(which npiet)"
